[mypy]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-feedparser.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-ragas.*]
ignore_missing_imports = True

[mypy-optimum.*]
ignore_missing_imports = True

[mypy-rank_bm25.*]
ignore_missing_imports = True

[mypy-crewai.*]
ignore_missing_imports = True

[mypy-youtube_search.*]
ignore_missing_imports = True
